### ISSUE TITLE
NTR: [Cattle / Beef cattle / Dairy cattle]

### ISSUE THREAD

**Issue by rahatzaheer** [cidgoh/GRDI_AMR_One_Health#25]
<You may request multiple terms in a single issue. Delete the fields irrelevant to your request.>

## New Picklist Term(s)
Cattle / Beef cattle / Dairy cattle
### REQUIRED: animal_or_plant_population
Associated Field(s):
Term Label: Cattle / Beef cattle / Dairy cattle
Definition/Description: <Can be a brief description to help curators differentiate your intended term from other meanings.>

### OPTIONAL:
Definition Source:
Synonyms or alternative labels:
Additional Comments (not an annotation):
Contributor Attribution: <ORCiD is preferred><Contributor information is added the the term when created when possible.>

**Comment by griffie** [comment]
Thanks @rahatzaheer we'll get these added ASAP!

**Comment by griffie** [comment]
Done.
