### ISSUE TITLE
NTR: [Enterococcus species]

### ISSUE THREAD

**Issue by rahatzaheer** [cidgoh/GRDI_AMR_One_Health#26]
<You may request multiple terms in a single issue. Delete the fields irrelevant to your request.>

## New Picklist Term(s)
Enterococcus asini NCBI:txid57732
Enterococcus cecorum NCBI:txid44008
Enterococcus caccae NCBI:txid317735
Enterococcus canis NCBI:txid214095
Enterococcus durans NCBI:txid53345
Enterococcus dispar NCBI:txid44009
Enterococcus hirae NCBI:txid1354
Enterococcus malodoratus NCBI:txid71451
Enterococcus mundtii NCBI:txid53346
Enterococcus ratti NCBI:txid150033
Enterococcus saccharolyticus NCBI:txid41997
Enterococcus thailandicus NCBI:txid417368
Enterococcus villorum NCBI:txid112904
### REQUIRED:
Associated Field(s): Organism
Term Label: Enterococcus species
Definition/Description: The requested picklist terms can be added to the existing 'sub-picklist' of Enterococcus [NCBITaxon:1350]. There are more Enterococcus species than these but these recommended species terms along with already included species can serve the purpose of commonly and somewhat rarely isolated Enterococcus species in our samples and also in the literature.

### OPTIONAL:
Definition Source:
Synonyms or alternative labels:
Additional Comments (not an annotation):
Contributor Attribution: <ORCiD is preferred><Contributor information is added the the term when created when possible.>

**Comment by griffie** [comment]
Thanks @rahatzaheer we'll get these added to the organism list!

**Comment by griffie** [comment]
Done!
