### ISSUE TITLE
CTR: [picklist correction for AMR_laboratory_typing_platform]

### ISSUE THREAD

**Issue by rahatzaheer** [cidgoh/GRDI_AMR_One_Health#27]
<You may request multiple terms in a single issue. Delete the fields irrelevant to your request.>

### REQUIRED - Current Term Information: Current picklist is relevant to "AMR_phenotype" instead of "AMR_laboratory_typing_platform"
Associated Field(s): AMR_laboratory_typing_platform
Term Label:
Antibiotic resistance not defined [GENEPIO:0002040]
      Intermediate antimicrobial phenotype [ARO:3004300]
      Indeterminate antimicrobial phenotype [GENEPIO:0100585]
Nonsusceptible antimicrobial phenotype [ARO:3004303]
Resistant antimicrobial phenotype [ARO:3004301]
Susceptible antimicrobial phenotype [ARO:3004302]
Susceptible dose dependent antimicrobial phenotype [ARO:3004304]
Not Applicable [GENEPIO:0001619]
Not Collected [GENEPIO:0001620]
Not Provided [GENEPIO:0001668]
Missing [GENEPIO:0001618]
Restricted Access [GENEPIO:0001810]
Ontology ID or PURL: 

### CHANGE REQUESTS:
Associated Field(s): AMR_laboratory_typing_platform
Term Label:
BIOMIC - Giles Scientific USA
Microscan [ARO:3004400]
Phoenix [ARO:3004401]
Sensitire [ARO:3004402]
Vitek System [ARO:3004403]
Not Applicable [GENEPIO:0001619]
Not Collected [GENEPIO:0001620]
Not Provided [GENEPIO:0001668]
Missing [GENEPIO:0001618]
Restricted Access [GENEPIO:0001810]

Definition/Description:
Synonyms or alternative labels:
Additional Comments (not an annotation):

Contributor Attribution: <ORCiD is preferred><Contributor information is added the the term when created when possible.>

**Comment by griffie** [comment]
Thanks @rahatzaheer we'll get this platform added to the picklist soon!

**Comment by griffie** [comment]
Added BIOMIC as platform and corrected picklists in template 7.6.4
