### ISSUE TITLE
NTR: Production Stream (Field)

### ISSUE THREAD

**Issue by chapb** [cidgoh/GRDI_AMR_One_Health#28]
Apologies for the lack of template structure, but this may be more of a discussion with input from others rather than a direct request.

Issues #24 and #25 get at an important concept I've been thinking about - "production streams". 

How do we most cleanly and efficiently differentiate between "production streams", like beef|dairy cattle production and layer|broiler chicken production?

I see that this difference is captured in `host (food production name)`, but I wonder if a separate field may be more useful, since the concept modifies both environment and host. Additionally, some terms would be repeated if we simply prepended the stream (e.g., beef heifers, dairy heifers).

It looks like the HSO ontology (https://github.com/SVA-SE/HSO) has struggled with this too. Their terms in the `livest` sheet of [this workbook](https://docs.google.com/spreadsheets/d/10jp_eRzAnoP1DAh6HaZ_dFbVzKGMkCLT12O-18cy8VE/edit#gid=1116515664) have been marked EOL, and two more documents discuss their work:

- https://docs.google.com/document/d/1gRN5qlh9UpziPmtVkNrbdzJKlRAX-4oyi8Hepl13TDo/edit#
- https://docs.google.com/document/d/10HJeeXuc9ZqxjiG8aLwpMY5Wx8WkzVKDNxH_EwJBA58/edit#heading=h.vatw0qrjs6m

I'm eager to hear what others think, as I'm approaching this from the analysis side rather than the data entry side.

**Comment by griffie** [comment]
Hi @chapb, I'm just doing a bit of asking around.
We know the HSO folks so will ask them directly, and also discuss at our GRDI meeting next week.

Hopefully be back with some suggestions soon!

**Comment by griffie** [comment]
@chapb we are still discussing this issue. :)
Question: in the example of layer vs broilers, would you want this field to point to the production of the animal (e.g. Layer (chicken) or Broiler (chicken)) or the product (e.g. eggs vs chicken meat)? You're talking about the production of the animal, right?

**Comment by chapb** [comment]
Apologies - this got buried in my notifications!

I would want the field to indicate the production of the animal. So for example, we'd later be able to differentiate isolates from ground chicken as coming through the broiler production stream, vs isolates from ground chicken produced from spent layer hens. We know these have very different exposures/lives, but at present it's hard to differentiate as they are the same food product, and the same animal species. 

We run into the same problem now with cattle - a "heifer" may be a dairy heifer and have those associated exposures, even if they end up in the beef system in the end as ground beef. And the cattle situation highlights the complexity of simply appending (beef|dairy) to an existing field, as cattle can cross over production systems at various points. So we'd have to add those for all other fields (e.g., dairy|beef calf, dairy|beef heifer, dairy|beef ground beef).

**Comment by griffie** [comment]
Added production stream and values to template 7.6.4
