### ISSUE TITLE
NTR: [Aeromonas rivipollensis]

### ISSUE THREAD

**Issue by gwajnberg** [cidgoh/GRDI_AMR_One_Health#42]
### Proposed Term Label

Aeromonas rivipollensis

### Proposed Associated Field(s)

organism

### Definition/Description

Just received a metadata from DFO sequencing with many bacteria absent in the pick list

**Comment by Anoosha-Sehar** [comment]
This term has been added and can be viewed in the most recent version of the GRDI template (v8.9.8).
