### ISSUE TITLE
NTR: [Pseudoalteromonas tetraodonis]

### ISSUE THREAD

**Issue by gwajnberg** [cidgoh/GRDI_AMR_One_Health#51]
### Proposed Term Label

Pseudoalteromonas tetraodonis

### Proposed Associated Field(s)

organism

### Definition/Description

Just received a template with many bacteria species absent from the picklist.

**Comment by Anoosha-Sehar** [comment]
This term has been added along with the referenced/parent term 'Pseudoalteromonas', and both of them can be viewed in the most recent version of the GRDI template (v8.9.8).
