### ISSUE TITLE
NTR: [Photobacterium sp.]

### ISSUE THREAD

**Issue by gwajnberg** [cidgoh/GRDI_AMR_One_Health#55]
### Proposed Term Label

Photobacterium sp.

### Proposed Associated Field(s)

organism

### Definition/Description

Just received a template with many bacteria species absent from the picklist.

**Comment by Anoosha-Sehar** [comment]
Many thanks @gwajnberg. We are working on curating your requests. These will be available upon the next public release.

**Comment by Anoosha-Sehar** [comment]
@gwajnberg This NTR has been added and can be viewed in the most recent version of the GRDI template (v8.9.8).
