### ISSUE TITLE
NTR: [ENVIRONMENTAL MATERIAL AND FOOD PRODUCT USED FOR ANIMALS SUGGESTED BY DOMINIC POULIN LA PRADE]

### ISSUE THREAD

**Issue by gwajnberg** [cidgoh/GRDI_AMR_One_Health#60]
### Bulk NTR URL

https://docs.google.com/spreadsheets/d/1yuWm76EO7jYQi0GHEFLvEbuzO5gCTLKNcL8oTvgNYM8/edit?usp=sharing

### Submission Requirements

- [X] Set the spreadsheet link sharing so that "Anyone with the link" can at least "View" or "Comment" if not "Edit".
- [X] <issue #> in the spreadsheet title has been replaced with the number of this issue.

- [X] Required columns (yellow highlight) have been provided for all of the requested terms.

**Comment by cbarcl01** [comment]
Sorry for the delay on this! Will add the terms and IDs to the next release, but in the meantime here are the IDs:

- barley seed | FOODON:00003394
- barley straw | FOODON:00004559 
- canola seed | FOODON:00004560

**Comment by cbarcl01** [comment]
Added to terms in v10.0.0
