### ISSUE TITLE
NTR: Manure Storage Lagoon

### ISSUE THREAD

**Issue by andscoaafc** [cidgoh/GRDI_AMR_One_Health#7]
# AMR-GRDI Specification - New Term Request (NTR)
_May request multiple terms in a single issue - delete the fields irrelevant to your request._

## Picklist Item(s)

Associated Field(s): environmental_site

Label: Manure Storage Lagoon
Definition/Description: Large capacity, liquid manure storage 
Definition Source: http://omafra.gov.on.ca/english/engineer/facts/10-051.htm
Synonyms or alternative labels:
Additional Comments (not an annotation):

--- 
Contributor Attribution: Andrew Scott (AAFC)

**Comment by griffie** [comment]
We added "Manure lagoon (Anaerobic lagoon)" to "environmental site".

How does that sound?
