### ISSUE TITLE
Pick-list for field `food_packaging` in the Excel template is displaying the wrong values.

### ISSUE THREAD

**Issue by ejurga** [cidgoh/GRDI_AMR_One_Health#73]
In the Excel template, the pick-list for the column `food_packaging` is displaying the wrong values, instead showing items from `collection_method`.

**Comment by cbarcl01** [comment]
Thanks for highlighting this! Will resolve that ASAP

**Comment by cbarcl01** [comment]
To update - this will be in the next release which will be available from next week

**Comment by cbarcl01** [comment]
Hi @ejurga - apologies for the delay on this, we were looking to add some additional information in this new release so I was hoping to do this all in one go. As it seems this may take a little longer I'll work on getting this change out to you as soon as possible. Thanks for your patience!

**Comment by cbarcl01** [comment]
This has been fixed in the newest release - thanks for picking up.
