### ISSUE TITLE
NTR: Shrimp 

### ISSUE THREAD

**Issue by ejurga** [cidgoh/GRDI_AMR_One_Health#74]
### Proposed Term Label

Shrimp [FOODON:03411237]

### Proposed Associated Field(s)

animal_source_of_food

### Definition/Description

A small decapod crustacean generally characterized by a laterally compressed body, muscular abdomen terminating fan-like tail, and delicate appendages adapted for swimming. 

### Definition Source

https://www.britannica.com/animal/shrimp-crustacean; Rudloe, J., & Rudloe, A. (2009). Shrimp: The endless quest for pink gold. FT Press.

### Additional Comments (not an annotation)

The foodon definition provides no formal definition. The taxonomy of shrimp is still disputed, so I am proposing we use a FOODON term instead of an NCBITaxon term here. I pulled the definition mainly from Encyclopedia Brittanica, supplemented with some other reading I did. 

The term already exists in food_product.

**Comment by cbarcl01** [comment]
The terms requested have been added to the newest release.
