### ISSUE TITLE
NTR: Scallops 

### ISSUE THREAD

**Issue by ejurga** [cidgoh/GRDI_AMR_One_Health#75]
### Proposed Term Label

Scallop [FOODON:03411489] OR Pectinidae [NCBITaxon:6566]

### Proposed Associated Field(s)

animal_source_of_food, food_product

### Definition/Description

Scallop is a common name that is primarily applied to any one of numerous species of saltwater clams or marine bivalve mollusks in the taxonomic family Pectinidae, the scallops. However, the common name "scallop" is also sometimes applied to species in other closely related families within the superfamily Pectinoidea, which also includes the thorny oysters.

### Definition Source

https://en.wikipedia.org/wiki/Scallop

### Additional Comments (not an annotation)

This is defined in the FOODON term, and that definition is in turn ripped from the wikipedia page, which is, in turn, not cited. But Encyclopedia britannica says much the same thing. 

Scallops at least are a monophyletic group, so we perhaps we could use the NCBITaxon term for it (which is Pectinidae, NCBITaxon_6566 ) in the animal_source_of_food, since most of these terms seem to be NCBITaxons themselves.

**Comment by cbarcl01** [comment]
Thanks for this - will add to the next release.

**Comment by cbarcl01** [comment]
The terms requested have been added to the newest release.
