### ISSUE TITLE
NTR: [Christine Liu's from DFO template with new terms]

### ISSUE THREAD

**Issue by gwajnberg** [cidgoh/GRDI_AMR_One_Health#76]
### Bulk NTR URL

https://docs.google.com/spreadsheets/d/1biekZa7KkOtr8fNQdFDTiZ8gdIWr6WbNWTdLGTyU5RQ/edit?usp=sharing

### Submission Requirements

- [X] Set the spreadsheet link sharing so that "Anyone with the link" can at least "View" or "Comment" if not "Edit".
- [X] <issue #> in the spreadsheet title has been replaced with the number of this issue.

- [X] Required columns (yellow highlight) have been provided for all of the requested terms.

**Comment by cbarcl01** [comment]
The terms have been added to the template and are available under the newest release https://github.com/cidgoh/GRDI_AMR_One_Health/tree/v10.0.0
