### ISSUE TITLE
NTR: Squid

### ISSUE THREAD

**Issue by ejurga** [cidgoh/GRDI_AMR_One_Health#85]
### Proposed Term Label

Squid [FOODON:03411205] 

### Proposed Associated Field(s)

animal_source_of_food, food_product

### Definition/Description

A squid is a mollusc with an elongated soft body, large eyes, eight arms, and two tentacles in the superorder Decapodiformes. 

### Definition Source

https://en.wikipedia.org/wiki/Squid

### Additional Comments (not an annotation)

The Foodon term has no definition (Should that be added to the official FOODON term?). Definition supplied is ripped from wikipedia, which cites no source.

**Comment by cbarcl01** [comment]
To be included in newest release

**Comment by cbarcl01** [comment]
Release 12.2.2
