### ISSUE TITLE
NTR: Mussels

### ISSUE THREAD

**Issue by ejurga** [cidgoh/GRDI_AMR_One_Health#86]
### Proposed Term Label

Mussel [FOODON:03411223]

### Proposed Associated Field(s)

animal_source_of_food, food_product

### Definition/Description

Mussel is the common name used for members of several families of bivalve molluscs, from saltwater and freshwater habitats. These groups have in common a shell whose outline is elongated and asymmetrical compared with other edible clams, which are often more or less rounded or oval.

### Definition Source

https://en.wikipedia.org/wiki/Mussel

### Additional Comments (not an annotation)

The definition of mussel in FOODON appears to be inherited from some other term (A whole mussel. An organism which is dead or alive and has a relatively intact body). The above definition is ripped from wikipedia, but also shows up in the Class "elucidation" field.

**Comment by cbarcl01** [comment]
Release 12.2.2
