### ISSUE TITLE
NTR: Vibrio parahaemolyticus

### ISSUE THREAD

**Issue by ejurga** [cidgoh/GRDI_AMR_One_Health#87]
### Proposed Term Label

Vibrio parahaemolyticus [NCIT:C86846]

### Proposed Associated Field(s)

organism

### Definition/Description

A species of facultatively anaerobic, Gram negative, curved rod shaped bacteria assigned to the phylum Proteobacteria. This species is motile, oxidase and lysine decarboxylase positive, hemolytic, halophilic and can use a wide variety of sugars as carbon sources. V. parahaemolyticus is a marine organism and a pathogen that causes gastroenteritis and wound infections.

### Additional Comments (not an annotation)

Definition from the NCIT term definition.

**Comment by cbarcl01** [comment]
Thanks for adding @ejurga - I'll prep for a mid June release :)

**Comment by cbarcl01** [comment]
NCBITaxon:670 used instead but with this definition.

**Comment by cbarcl01** [comment]
Release 12.2.2
